name: biformer
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cachetools=4.2.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - flit-core=3.6.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - grpcio=1.42.0
  - idna=3.4
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.1
  - openh264=2.1.1
  - openssl=1.1.1t
  - pillow=9.4.0
  - pip=22.3.1
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.8.16
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - werkzeug=2.2.2
  - wheel=0.38.4
  - xz=5.2.10
  - yarl=1.8.1
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - addict==2.4.0
      - antlr4-python3-runtime==4.9.3
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - contourpy==1.0.7
      - cycler==0.11.0
      - cython==0.29.34
      - einops==0.6.0
      - fairscale==0.4.13
      - filelock==3.9.0
      - fonttools==4.39.0
      - fvcore==0.1.5.post20221221
      - huggingface-hub==0.12.1
      - hydra-core==1.3.2
      - importlib-resources==5.12.0
      - iopath==0.1.10
      - kiwisolver==1.4.4
      - markdown-it-py==2.2.0
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - mmcls==0.25.0
      - mmcv-full==1.7.0
      - mmdet==2.25.3
      - mmpycocotools==12.0.3
      - mmsegmentation==0.30.0
      - model-index==0.1.11
      - omegaconf==2.3.0
      - opencv-python==4.7.0.72
      - ordered-set==4.1.0
      - packaging==23.0
      - pandas==1.5.3
      - portalocker==2.7.0
      - prettytable==3.6.0
      - pygments==2.14.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - pyyaml==6.0
      - rich==13.3.2
      - safetensors==0.3.0
      - scipy==1.10.1
      - submitit==1.4.5
      - tabulate==0.9.0
      - termcolor==2.2.0
      - terminaltables==3.1.10
      - timm==0.8.15.dev0
      - tqdm==4.65.0
      - triton==1.1.1
      - wcwidth==0.2.6
      - yacs==0.1.8
      - yapf==0.32.0
